### ISSUE TITLE
Refuses to run on Python 3.12

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/nose2pytest#28]
I installed with `pipx install nose2pytest@git+https://github.com/pytest-dev/nose2pytest --force` (GitHub link because PyPI is stale), but then the project failed to run:

```
nose2pytest .
Traceback (most recent call last):
  File "/Users/jaraco/.local/bin/nose2pytest", line 7, in <module>
    from nose2pytest.script import main
  File "/Users/jaraco/Library/Application Support/pipx/venvs/nose2pytest/lib/python3.12/site-packages/nose2pytest/script.py", line 133, in <module>
    raise RuntimeError('nose2pytest must be run using Python 3.5 to 3.11')
RuntimeError: nose2pytest must be run using Python 3.5 to 3.11
```

**Comment by jaraco** [comment]
I was able to temporarily work around the problem by uninstalling and then installing with:

```
pipx install --python 3.11 nose2pytest@git+https://github.com/pytest-dev/nose2pytest
```

**Comment by nicoddemus** [comment]
Seems to be fixed in https://github.com/pytest-dev/nose2pytest/commit/75ff506aaf11b5e20672441730657ee7540387e1.
